### ISSUE TITLE
meltano - explore tutorial and present

### ISSUE THREAD

**Issue by machow** [CodeForPhilly/cfp-data-pipeline#2]
## Task

Implement a tutorial from http://meltano.com/tutorials/ on your own laptop, and screenshare / present on it in a group meeting. For example, [this tutorial](http://meltano.com/tutorials/csv-with-postgres.html) looks very relevant!

Here are some key performance conditions that might be important:

* How long did it take to set up?
* What did you do with it?
* Who is it for?

## What is meltano?

[![image](https://user-images.githubusercontent.com/2574498/103700653-05f0f980-4f62-11eb-9540-cd371a884abe.png)](http://meltano.com)

**Comment by dherbst** [comment]
I'll take a look at this.

**Comment by dherbst** [comment]
Here are some of my answers to the questions above:

# How long did it take to set up?

At first used python3.9 but realized that meltano does not work with 3.9.  I created a [dockerfile](https://github.com/dherbst/cfp-data-pipeline/blob/meltano/meltano/Dockerfile) to install it on python 3.8 that takes a few minutes.   But then I read a bit more and they have a docker image they publish at `meltano/meltano` so you can start using that immediately.

# What did you do with it?

I explored the first part of the csv-project tutorial - which is to create an empty meltano project, and then load in three csv files into a postgres database.  This took about an hour because the tutorial doesn't match the current version of meltano's UI and I had to learn what a tap was.

# Who is it for?

If a project uses meltano, then when someone new joins the project you can explain what the different directories are for in the project as they relate to the different ELT tools.  This could make onboarding and training much easier, especially if someone has used meltano before.  It also offers some standardization of how the different tools like singer, dbt, and airflow are configured and run in the production system.   It should be helpful for almost everyone on the project as they can ask questions about how data flows through the system and almost everyone on the project will have a common understanding of how all the different tools are set up and interact.

Here are more notes for the presentation: https://github.com/dherbst/cfp-data-pipeline/blob/meltano/meltano/README.md

**Comment by dherbst** [comment]
@machow going to close this, as the presentation was done on 1/19/2021.
