### ISSUE TITLE
Modify singer tap for slack to use only public channels

### ISSUE THREAD

**Issue by machow** [CodeForPhilly/cfp-data-pipeline#4]
Currently, I ingest Code for Philly's slack data using custom R scripts. If we could use a [singer tap](https://www.singer.io/), then we could cut out all that custom code.

The challenge is that we only want to access public data, but the singer tap hard-codes that it's pulling private data.

https://github.com/singer-io/tap-slack

**Comment by dherbst** [comment]
What kind of private data do you want to avoid, or make anonymous?   There is a `private_channels: false` configuration.

You can see a meltano configuration here: https://github.com/dherbst/cfp-data-pipeline/blob/tap-slack/meltano/cfp-slack/meltano.yml that sends it to csv files.

**Comment by machow** [comment]
Note: Currently pulling all user emails. Likely want to remove.

**Comment by dherbst** [comment]
We can do this with meltano's `select` extra: https://meltano.com/docs/plugins.html#extractors

Something like:
```yaml
   - name: tap_slack
     select:
         - users.profile.!email
 ```

But an interesting thing is that slack is not pulling in the user emails by default now that I moved it up to slack.v3 because the tap does not have the `profile` object.   So we can wait on this for now.

**Comment by machow** [comment]
Whoops--circling back to close, thanks for implementing this!
